INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (1001, 'ajay', 'AWS Certified', CURRENT_DATE, false);

INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (1002, 'ajay', 'GCP Certified', CURRENT_DATE, false);

INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (1003, 'ajay', 'Azure Certified', CURRENT_DATE, false);

INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (1004, 'ajay', 'Devops Learning', CURRENT_DATE, false);
